"""debug_tools.py — SimVision debug Tcl script and Markdown document generators.

Used by generate_debug_tcl and export_debug_context MCP tools (Phase 3/5).

Architecture note:
  All generated files are written to cloud0 local filesystem.
  Output paths are cloud0 paths, not local (client) paths.
"""

from __future__ import annotations

import time as _time

from xcelium_mcp.shell_utils import sanitize_signal_name, validate_path


def _tcl_escape(s: str) -> str:
    """Escape a string for safe embedding inside Tcl double-quotes.

    Escapes: backslash, double-quote, dollar-sign, open-bracket.
    """
    return (
        s.replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("$", "\\$")
        .replace("[", "\\[")
    )


# ---------------------------------------------------------------------------
# Tcl script generation (§8-B offline debug)
# ---------------------------------------------------------------------------

def generate_debug_tcl_content(
    shm_path: str,
    signals: list[str],
    center_time_ns: int,
    zoom_range_ns: int = 10000,
    markers: list[dict] | None = None,
    context_note: str = "",
) -> str:
    """Generate SimVision Tcl script content for offline debugging.

    The caller writes the returned string to a .tcl file and instructs the
    user to run: simvision -input {tcl_path} {shm_path}

    Args:
        shm_path:       SHM dump file path (used in database -open command).
        signals:        Signal paths to add to waveform viewer.
        center_time_ns: Bug time — waveform is zoomed to ±zoom_range_ns around it.
        zoom_range_ns:  Half-width of zoom range in nanoseconds.
        markers:        List of {"time_ns": int, "label": str} dicts.
        context_note:   AI analysis summary printed to SimVision console.
    """
    if markers is None:
        markers = []

    # Validate shm_path
    path_err = validate_path(shm_path, "shm_path")
    if path_err:
        raise ValueError(path_err)

    # Sanitize signals
    sanitized_signals = [sanitize_signal_name(s) for s in signals]

    ts = _time.strftime("%Y-%m-%d %H:%M:%S")
    lines = [
        "# === Auto-generated debug script ===",
        f"# Center time: {center_time_ns}ns",
    ]
    if context_note:
        lines.append(f"# Context: {_tcl_escape(context_note)}")
    lines.append(f"# Generated by xcelium-mcp at {ts}")
    lines.append("")

    # Open SHM waveform
    lines.append(f"database -open {shm_path} -shm")
    lines.append("")

    # Add debug signals
    if sanitized_signals:
        lines.append("# Add debug signals")
        lines.append("waveform add -signals {")
        for sig in sanitized_signals:
            lines.append(f"    {sig}")
        lines.append("}")
        lines.append("")

    # Zoom to bug region
    start_zoom = center_time_ns - zoom_range_ns
    end_zoom = center_time_ns + zoom_range_ns
    lines.append("# Zoom to bug region")
    lines.append(f"waveform zoom -range {start_zoom}:{end_zoom}ns")
    lines.append("")

    # Main cursor at bug time
    lines.append("# Set cursor at bug time")
    lines.append(f"cursor set -time {center_time_ns}ns")
    lines.append("")

    # Named markers
    if markers:
        lines.append("# Markers")
        for m in markers:
            t = m.get("time_ns", 0)
            label = _tcl_escape(m.get("label", ""))
            lines.append(f'cursor set -time {t}ns -name "{label}"')
        lines.append("")

    # AI context note
    if context_note:
        lines.append("# AI analysis context (console output)")
        lines.append('puts "============================================"')
        lines.append('puts "AI Debug Context:"')
        for chunk in context_note.split(". "):
            chunk = chunk.strip()
            if chunk:
                lines.append(f'puts "  {_tcl_escape(chunk)}"')
        lines.append('puts "============================================"')

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Markdown debug context document (§8 export)
# ---------------------------------------------------------------------------

def generate_debug_context_md(
    test_name: str,
    bug_description: str,
    root_cause: str,
    evidence: list[dict],
    related_code: list[dict],
    signals_to_check: list[str],
    suggested_fix: str = "",
) -> str:
    """Generate a human-readable debug context Markdown document.

    Args:
        test_name:        Test name (e.g. "TOP015").
        bug_description:  One-line summary.
        root_cause:       AI-inferred root cause.
        evidence:         List of {"time_ns", "signal", "value", "expected", "meaning"}.
        related_code:     List of {"file", "line", "snippet"}.
        signals_to_check: Signals for the user to verify in SimVision.
        suggested_fix:    Optional fix suggestion.
    """
    lines = [
        f"# Debug Context: {test_name}",
        "",
        "## Bug Summary",
        bug_description,
        "",
        "## Root Cause (AI 추정)",
        root_cause,
        "",
    ]

    if evidence:
        lines += [
            "## Evidence (CSV 분석)",
            "| 시각 (ns) | 신호 | 실측값 | 기대값 | 의미 |",
            "|-----------|------|--------|--------|------|",
        ]
        for ev in evidence:
            t = ev.get("time_ns", 0)
            sig = ev.get("signal", "")
            val = ev.get("value", "")
            exp = ev.get("expected", "")
            meaning = ev.get("meaning", "")
            lines.append(f"| {t} | {sig} | {val} | {exp} | {meaning} |")
        lines.append("")

    if related_code:
        lines += ["## Related Code"]
        for rc in related_code:
            f = rc.get("file", "")
            ln = rc.get("line", "")
            s = rc.get("snippet", "")
            lines.append(f"- {f}:{ln} — `{s}`")
        lines.append("")

    if signals_to_check:
        lines += ["## Signals to Check in SimVision"]
        for i, sig in enumerate(signals_to_check, 1):
            lines.append(f"{i}. {sig}")
        lines.append("")

    if suggested_fix:
        lines += ["## Suggested Fix", suggested_fix, ""]

    return "\n".join(lines)
